### ISSUE TITLE
Date not pushing to salesforce

### ISSUE THREAD

**Issue by gdaychef** [cimburadotcom/salesforce-wordpress-to-lead#40]
Hi nciske
i am having an issue with the date not pulling into the salesforce field

Jason

**Comment by nciske** [comment]
I'm not surprised, Salesforce date fields are a real pain. 

The plugin just passes the value - you need to make sure it's formatted correctly for your account/locale. 

Some more info about the issue:
https://wordpress.org/support/topic/text-field-and-jquery-datetime-picker

GitHub is for reporting bugs & feature requests. The WP.org forum is for support.

I'd like to improve date handling so feel free to open a feature request ticket, but if you want support please use the forum (open a new thread). 

Thanks
