### ISSUE TITLE
 Avoid Lead Duplicacy

### ISSUE THREAD

**Issue by karan4official** [cimburadotcom/salesforce-wordpress-to-lead#42]
Please set a check that if the lead with same email-id alredy exist in salesforce then instead of creating a duplicate lead it should updtate that lead

**Comment by nciske** [comment]
Nope, the the web to lead API is write only. Any deduplication logic needs to be on the salesforce side.

**Comment by nciske** [comment]
Can’t fix without using the full REST API, which would be an add-on or PRO version.
