### ISSUE TITLE
Add Lead URL in admin mail

### ISSUE THREAD

**Issue by karan4official** [cimburadotcom/salesforce-wordpress-to-lead#43]
Get Salesforce Lead URL in admin mail which gets created once user fill this WordPress-to-lead for Salesforce CRM Form

**Comment by nciske** [comment]
See the FAQ - you can add this now by adding a hidden field with a merge variable. 

It should probably be in the email regardless, I'll add it to the list for 3.0.

**Comment by karan4official** [comment]
Thanks for replying, 
I have seen the FAQ, but can't found any information about "hidden field with a merge variable." or to "Get Salesforce Lead URL" it have information about  "the full URL the form is embedded on" by using %url% but i am not looking for this. I want salesforce lead url ( like : https://na31.salesforce.com/00Q3700000CnjJx?srPos=0&srKp=00Q). to be added in admin mail

**Comment by nciske** [comment]
Ah. That's not possible with the web to lead API. Sorry.

**Comment by nciske** [comment]
Can’t fix without using the full REST API, which would be an add-on or PRO version.

**Comment by nciske** [comment]
Can’t fix without using the full REST API, which would be an add-on or PRO version.
