### ISSUE TITLE
URGENT "WordPress-to-Lead for Salesforce CRM" not working in live website

### ISSUE THREAD

**Issue by marketingNPAW** [cimburadotcom/salesforce-wordpress-to-lead#46]
Hi, we configured the plugin WordPress-to-Lead for Salesforce CRM last week and it worked perfectly. Since Monday (yesterday), it doesn't work anymore. We don't understand why. It is imperative to have it working asap as the website to be live depends on it! Someone can help???

PS. I have checked and unchecked this "Enable verification of SalesForce SSL certificate when connecting (fixes connection issues on some sites behind F7 firewalls and BigIP load balancers)" and issue persists. It looks it's loading on the website eternally: http://nicepeopleatworkblog.nicepeopleatwork.com/index.php/request-a-demo/. And Salesforce company ID is properly set up.

**Comment by nciske** [comment]
Looks like you've enabled the CF7 integration... which can cause CF7 to hijack the submit button. Their greedy jQuery selector hijacks all submit buttons with that class.

```
= 2.6.7 =
* Add setting to remove WP CF7 javascript to fix it hijacking forms with WP CF7 CSS integration turned on
```

Try checking the "Remove WP CF7 Javascript on SFWP2L pages? (fixes CF7 hijacking form submits, may break CF7 forms on the same page)" option... or not using the _CF7 Integration_ option.

**Comment by marketingNPAW** [comment]
Thanks! How do you manage to inherit the css of the form from general rules of the website then? Because if this is not set up, it looks disruptive in terms of look and feel / branding.

**Comment by nciske** [comment]
Not sure what you’re asking? If you want it to look like a CF7 form, use the integration and the option to remove the unneccesary Javascript.

Or use the custom CSS option to style your Salesforce forms as you want.

By default they have very minimal styling and blend in seamlessly with most themes.

The CF7 "integration" option was a pull request I never should have accepted, but I'm stuck with it now.

**Comment by marketingNPAW** [comment]
it works... I will see how to solve the css thing now! thanks!
