### ISSUE TITLE
Auto-populate from query string

### ISSUE THREAD

**Issue by bkCDL** [cimburadotcom/salesforce-wordpress-to-lead#49]
First, this is a great plugin. It makes things very easy for our corporate site. I'm wondering, though, is it possible to populate a wordpress-to-lead via the URL querystring? 

I'm thinking of a particular use case where a link from a products table might direct to a sales contact form with a URL such as:

    `http://example.com/contact/sales?message=I+want+the+platinum+product`

Then, when the form loads, it reads the field name in the query string and pre-populates it on the screen. 

Might this be possible?

Bryan

**Comment by bkCDL** [comment]
Oh sorry. I see the docs for this now in the README.txt.

**Comment by nciske** [comment]
Yes, I'd like to make it easier in a future version... for now you need to use filters...
