### ISSUE TITLE
Updating the Web-to-Case and Web-to-Lead Endpoint URL

### ISSUE THREAD

**Issue by djangle** [cimburadotcom/salesforce-wordpress-to-lead#57]
Salesforce has planned an update for June 2017 which will render the "https://www.salesforce.com/servlet/servlet.WebToLead" and "https://www.salesforce.com/servlet/servlet.WebToCase" endpoints unusable. 

Can the form's endpoint be modified now, and if not will an update to the salesforce-wordpress-to-lead project be released to use the new endpoints? i.e. "https://webto.salesforce.com/servlet/servlet.WebToLead"

[https://help.salesforce.com/apex/HTViewSolution?urlname=Updating-the-Web-to-Case-and-Web-to-Lead-Endpoint-URL&language=en_US&eid=ss-tc](url)

**Comment by nciske** [comment]
There is a filter for the API endpoint url you can use today (see the "other notes" tab on the WordPress plugin page). 

This will be updated in the next release.

**Comment by djangle** [comment]
Thanks Nick!

[https://wordpress.org/plugins/salesforce-wordpress-to-lead/other_notes/](url)
