### ISSUE TITLE
Issue with required fields styling

### ISSUE THREAD

**Issue by ginnyhalp** [cimburadotcom/salesforce-wordpress-to-lead#63]
Hi there - required fields are showing up with double asterisks. I can't for the life of me figure out how to change the styling. Any ideas? 
![screen shot 2017-01-31 at 4 19 39 pm](https://cloud.githubusercontent.com/assets/25468273/22486954/1d976328-e7d1-11e6-840d-e3762d77578d.png)

**Comment by nciske** [comment]
Do you have asterisks in your field labels?

Possibly a stylesheet some another plugin interfering?

What's the URL of this form?

**Comment by ginnyhalp** [comment]
I don't have asterisks in my field labels. Could be another plugin... I'm filling in on a client project, and I don't know much about what else they have going on in wordpress...

This is the URL: http://veracare.com/signup-colorado-springs/

**Comment by nciske** [comment]
Here's your issue:

style.css line 409

```
label.required:after {
	content: '*';
	display: inline-block;
	vertical-align: text-top;
	font-size: 80%;
	color: #da6f5b;
}
```

To fix, you can hide the plugin's asterisks with some custom CSS:

```
.salesforce_w2l_lead span.required{
	display: none;
}
```

**Comment by ginnyhalp** [comment]
Yes! That worked. Thanks so much for the quick help!
