### ISSUE TITLE
Hidden fields not mapping

### ISSUE THREAD

**Issue by ginnyhalp** [cimburadotcom/salesforce-wordpress-to-lead#64]
Hi! My hidden fields aren't mapping to my SF lead fields. This is how my form is set up:
![screen shot 2017-02-01 at 4 44 28 pm](https://cloud.githubusercontent.com/assets/25468273/22529643/de655df4-e89d-11e6-89a2-dff8d289e94d.png)
 
And this is my fields in SF:
![screen shot 2017-02-01 at 4 45 17 pm](https://cloud.githubusercontent.com/assets/25468273/22529652/ea74a316-e89d-11e6-9feb-22d7a5abd363.png)

They should both be populating, but they're not. It's probably user error. Any ideas about what I'm doing wrong?

**Comment by markjohnnightingale** [comment]
Chère cliente, cher client, 

Je suis en déplacement ce jeudi et vendredi 2 et 3 février, avec un accès restreint à ma boîte mail. 

Je prendrai connaissance de votre demande le lundi 6 février 2017.
Bon weekend, 

Mark Nightingale

**Comment by nciske** [comment]
I suspect you'll have better luck using the correct field names.

From the FAQ:

**How do I use a SalesForce custom field?**

- Go to Setup » Customize » Leads » Fields
- If your custom field does not exist yet, create it now.
- Find the API Name for your field (e.g. Custom_Field_Example__c). If it doesn't end in "__c" it's not the API name and _will not work_.
- Add a new field to your form using the form editor on the plugin admin screen
- Enter the API Name as the field name (left most box), then fill out the other fields normally (make sure to enable the field!).
- Save your changes -- new submissions will now post that custom field to SalesForce

**Comment by ginnyhalp** [comment]
Got it - thanks!
