### ISSUE TITLE
checkboxes do not work

### ISSUE THREAD

**Issue by qwikag** [cimburadotcom/salesforce-wordpress-to-lead#66]
Please feel free to advise if I have posted incorrectly. Noob.

My main issue is checkbox do not post anything.
I will however describe many issues encountered.

If using the import from the web-to-Lead generator, we get ids in our name fields which is normal for std HTML.
So this suggests ids are required in the form editor.
But the docs say use the api name.
All very confusing.
I have tried both methods and both do not work, including std checkboxes.
I will strip back my page and start again.
I might try trapping the post.
I wonder if the new sfdc endpoint is broken. I will try the old.

1 caveat, someone else owned this SF-WP-to-Lead install, I have since upgraded it to the latest version because it was not working.

**Comment by nciske** [comment]
Plugin support is handled via the WordPress support forum.
https://wordpress.org/support/plugin/salesforce-wordpress-to-lead

GitHub issues are for bug reports and pull requests.

**Comment by qwikag** [comment]
I get that, but checkboxes do not work as per your documentation, so maybe it is an "Issue", maybe it is not, either way I would suspect you need a fix.
Happy to help if you can throw me a bone.

**Comment by nciske** [comment]
Until it's a verified bug, it doesn’t belong here. Please use the WP.org forum. Thanks.
