### ISSUE TITLE
Salesforce no longer sending lead assignment notifications

### ISSUE THREAD

**Issue by WraithActual** [cimburadotcom/salesforce-wordpress-to-lead#67]
Hi there, 

After installing this plugin, instead of sending enquires to Salesforce using our own method, the new leads that are generated and then re-assigned are not generating a notification email.

Is this something you have come across before?

Many thanks

Tom

**Comment by nciske** [comment]
This plugin sends leads to Salesforce -- sounds like that is happening?

What happens after that is not something we can offer support for -- sorry!
